#!/bin/sh
#
# Starts TVOS app.
#

start() {

	export TSLIB_TSDEVICE=/dev/touchscreen-1wire
	export TSLIB_TSEVENTTYPE=INPUT
	export TSLIB_FBDEVICE=/dev/fb0
	export TSLIB_PLUGINDIR=/usr/lib/ts/
	export TSLIB_CONSOLEDEVICE=none
	export TSLIB_CONFFILE=/etc/ts.conf
	export TSLIB_CALIBFILE=/etc/pointercal
	export LD_LIBRARY_PATH=/usr/lib
	export QTDIR=/usr/lib/qt
	export QWS_MOUSE_PROTO=tslib:/dev/touchscreen-1wire

 	echo -n "Starting tvos app: "

        # Make sure tvos directory exists
        if [ ! -d /etc/tvos ] ; then
                mkdir -p /etc/tvos
        fi
        umask 077

	start-stop-daemon -S -p /var/run/tvos.pid --exec /opt/TVOS -- -qws
	[ $? == 0 ] && echo "OK" && psplash-write "QUIT" || echo "FAIL" && psplash-write "MSG ERROR"
	psplash-write "QUIT"
}
stop() {
	echo -n "Stopping tvos app: "
	start-stop-daemon -K -p /var/run/tvos.pid
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
